package alphasights.apps.utilities;

public enum alphasightsEnvironments {
    QA_PISTACHIO,
    QA_DELIVERY,
    QA_CLIENT_PLATFORM,
    STAGING_PISTACHIO,
    STAGING_DELIVERY,
    STAGING_CLIENT_PLATFORM,
    STAGING_REDELIVERY_NEW_PROJS,
    PROD_PISTACHIO,
    PROD_DELIVERY,
    PROD_CLIENT_PLATFORM,
    COMPANIES_DELIVERY
}
